### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by auroll** [suchmememanyskill/steam-deck-addons#6]
Hi there,

This addon worked fine until recently.
Today I wanted to use it again but when I run it it says:
"No usable version of libssl was found"

Then underneath it says it crashed.

**Comment by suchmememanyskill** [comment]
Which tool/addon are you using?

**Comment by auroll** [comment]
Right click Add to Steam

**Comment by polo421** [comment]
I'm having the same issue. Everything worked fine on my old Steam Deck but I added this tool on the new OLED steam deck and I'm getting the same issue when trying to right click add to steam.

**Comment by suchmememanyskill** [comment]
I have recompiled the application, please re-run the install script and let me know if that fixes the issue

**Comment by auroll** [comment]
IT seems like it's working now. However, I was also able to add to Steam normally with the regular Steam button.

**Comment by suchmememanyskill** [comment]
Thanks for testing, closing as resolved.

Also yea, steamos some time ago got this feature, this tool existed before that got introduced.
